### ISSUE TITLE
Stacking waterfalls

### ISSUE THREAD

**Issue by ghost** [HERA-Team/rids#1]
Can it be possible to give sp_rawview multiple .ridz (or .rids) files with the --w command, and for the script to generate a single waterfall containing every dataset in the given set of .ridz files?

**Comment by david-deboer** [comment]
I believe that you already can.  `sp_rawview.py file1,file2, -w val` _should_ use both.  I would believe that it only pretends to if that's what you find, but it seems to work...

**Comment by ghost** [comment]
Can confirm that this works if I do: "sp_rawview.py --wf val file_1,...,file_n" 
Thank you!
