### ISSUE TITLE
sp_rawview argparse argument for the title of the plot

### ISSUE THREAD

**Issue by ghost** [HERA-Team/rids#2]
Would you consider adding plot title as an argument one can pass to sp_rawview? Currently there's the convenient T_RANGE argument, but to make better use of this (e.g. plot night-only and day-only plots), I'd like to be able to add different titles to different plots.

**Comment by david-deboer** [comment]
There is now a --title argument.

**Comment by ghost** [comment]
Looking at the argument documentation, I expected that --title wanted a string as the argument. However, If I execute the following command in an ipynb notebook : 
%run <filename> --totalpower val --title str("Title") {str_args}

I receive the errors copied below. Note that if I run the same command without the title argument then I don't receive any errors and get the desired plot.


TypeErrorTraceback (most recent call last)
/users/ajosaiti/anaconda/envs/py2.7env/rids/scripts/sp_rawview.py in <module>()
     78     s.time_filter(args.wf)
     79     s.process(wf_time_fill=args.wf_time_fill, show_edits=args.show_edits)
---> 80     s.raw_waterfall_plot(title=args.title)
     81 if args.stack is not None:
     82     s.time_filter(args.stack)

TypeError: raw_waterfall_plot() got an unexpected keyword argument 'title'
Reading SDR_SpectrumPeak.20181028-220000.n240.None.ridz
Data span 2018-10-28 22:00:00 - 2018-10-28 23:59:30
TypeErrorTraceback (most recent call last)
/users/ajosaiti/anaconda/envs/py2.7env/rids/scripts/sp_rawview.py in <module>()
     90     s.time_filter(args.totalpower)
     91     s.process(show_edits=args.show_edits, total_power_only=True)
---> 92     s.raw_totalpower_plot(title=args.title)
     93 plt.show()

TypeError: raw_totalpower_plot() got an unexpected keyword argument 'title'
